""" add user assessment tables """
from alembic import op
import sqlalchemy as sa

revision = 'aa2caf1c3975'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='assessmentstatus'), nullable=False),
    sa.Column('training_experience', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='trainingexperience'), nullable=False),
    sa.Column('current_activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'HIGH', name='activitylevel'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('biological_sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'NOT_SPECIFIED', name='biologicalsex'), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('preferred_weight_unit', sa.Enum('KG', 'LB', name='weightunit'), nullable=False),
    sa.Column('preferred_distance_unit', sa.Enum('KM', 'MI', name='distanceunit'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('estimated_training_level', sa.String(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=True),
    sa.Column('training_considerations', sa.JSON(), nullable=True),
    sa.Column('nutrition_considerations', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='aiassessmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('available_equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_type', sa.Enum('BARBELL', 'DUMBBELL', 'BENCH', 'CABLE_MACHINE', 'RESISTANCE_BAND', 'CARDIO_MACHINE', 'BODYWEIGHT', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_available_equipment_assessment_id'), 'available_equipment', ['assessment_id'], unique=False)
    op.create_table('health_constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INJURY', 'PAIN', 'MOVEMENT_LIMITATION', 'MEDICAL_CONDITION', 'EXERCISE_RESTRICTION', name='healthconstrainttype'), nullable=False),
    sa.Column('body_area', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', name='severity'), nullable=True),
    sa.Column('reported_by_user', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_constraints_assessment_id'), 'health_constraints', ['assessment_id'], unique=False)
    op.create_table('nutrition_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('dietary_pattern', sa.Enum('NO_PREFERENCE', 'VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'HALAL', 'KOSHER', 'OTHER', name='dietarypattern'), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('disliked_foods', sa.JSON(), nullable=True),
    sa.Column('preferred_foods', sa.JSON(), nullable=True),
    sa.Column('budget_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='budgetlevel'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('progress_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('view', sa.Enum('FRONT', 'SIDE', 'BACK', 'OTHER', name='photoview'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ai_analysis_allowed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_assessment_id'), 'progress_photos', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'], unique=False)
    op.create_table('training_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_days', sa.JSON(), nullable=True),
    sa.Column('training_location', sa.Enum('COMMERCIAL_GYM', 'HOME_GYM', 'HOME', 'OUTDOORS', name='traininglocation'), nullable=False),
    sa.Column('preferred_training_style', sa.String(), nullable=True),
    sa.Column('exercises_to_avoid', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('user_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('LOSE_FAT', 'BUILD_MUSCLE', 'GAIN_STRENGTH', 'IMPROVE_FITNESS', 'MAINTAIN_WEIGHT', name='goaltype'), nullable=False),
    sa.Column('priority', sa.Enum('PRIMARY', 'SECONDARY', name='goalpriority'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_assessment_id'), 'user_goals', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_goals_assessment_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_table('training_preferences')
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_assessment_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_table('nutrition_preferences')
    op.drop_index(op.f('ix_health_constraints_assessment_id'), table_name='health_constraints')
    op.drop_table('health_constraints')
    op.drop_index(op.f('ix_available_equipment_assessment_id'), table_name='available_equipment')
    op.drop_table('available_equipment')
    op.drop_table('ai_assessments')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
